---
# defaults file for nextcloud
myDomain: example.com
homecloudUrl: homecloud.{{ myDomain }}
homecloudDBHost: localhost
homecloudAdditional_open_basedir: ''
homecloudDir: /usr/share/webapps/nextcloud
homecloudDataDir: "{{ homecloudDir }}/data"
homecloudDbtableprefix: "hc_"
homecloudLogDir: /var/log/homecloud
homecloudDataBase: homecloud
homecloudCert: /etc/nginx/ssl/{{ homecloudUrl }}.crt
homecloudKey: /etc/nginx/ssl/{{ homecloudUrl }}.key
homecloudAdminPassword: "{{ lookup('password', 'credentials/common/' + role_name + '/admin-password') }}"
homecloudApps: []
homecloud_open_basedir: "{{ homecloudLogDir }}:/proc/meminfo:/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/dev/urandom:/etc/webapps/nextcloud/config/:{{ homecloudDir }}/config/:{{ homecloudAdditional_open_basedir }}"
cryptName: usbstorageDisk
otherServers: "{{ groups['all'] }}"
letsencryptVirtualhosts: []
nextcloudDefaultApps: [ 'bookmarks', 'calendar', 'contacts', 'notes' ]
