---
# handlers file for shinken
- name: restart shinken
  service: name=shinken-{{item.name}} state={{item.state}}
  with_items:
    - { name: receiver, state: stopped}
    - { name: broker, state: stopped}
    - { name: scheduler, state: stopped}
    - { name: reactionner, state: stopped}
    - { name: poller, state: stopped}
    - { name: arbiter, state: stopped}
    - { name: arbiter, state: started}
    - { name: poller, state: started}
    - { name: reactionner, state: started}
    - { name: scheduler, state: started}
    - { name: broker, state: started}
    - { name: receiver, state: started}
- name: reload nginx
  service: name=nginx state=reloaded
