---
# defaults file for usbstorage
cryptPass: "{{ lookup('password', 'credentials/common/' + role_name + '/key') }}"
cryptName: usbstorageDisk
btrfsSubVolumes:
  - { name: 'data', mount: 'data'}
  - { name: 'backup', mount: 'backup'}
  - { name: 'masterbackup', mount: 'masterbackup'}
btrfsSubVolumesAdditionnals: []
dmDisk: "/dev/mapper/{{cryptName}}"
btrfsVolumesToHTTP: []
additionalBackup: []
rsyncBwLimit: 5000
snapDir: "snapshots"
snapVolumesExclude: []
hourlySnapToKeep: 24
dailySnapToKeep: 7
weeklySnapToKeep: 5
monthlySnapToKeep: 12

#bandwith limits
btrfsSshMaxUpload: -1
btrfsSshMaxDownload: -1

rwDirectories:
  - {name: var, size: 10G, path: /var}
  - {name: opt, size: 1G, path: /opt}
  - {name: srv, size: 1G, path: /srv}
