---
# defaults file for letsencrypt
cronState: "present"
letsencryptVirtualhosts: []
myDomain: "example.org"
letsEncryptEmail: "admin@{{ myDomain }}"
letsEncryptRsaKeySize: 2048
letsEncryptPreferedChallenges: "http"
renewBefore: 58
