---
# tasks file for ssmtp
- name: install ssmtp
  pacman: name=ssmtp state=present
- name: configure ssmtp
  template: src=etc/ssmtp/ssmtp.conf dest=/etc/ssmtp/ssmtp.conf owner=root group=root mode=0640
- name: copy iptables rules for {{role_name}}
  template: src=etc/iptables/iptables.rules.d/role_{{role_name}}.rule dest=/etc/iptables/iptables.rules.d/ owner=root group=root mode=0700
