---
# tasks file for iptables
- name: create directory /etc/iptables/iptables.rules.d/
  file: path=/etc/iptables/iptables.rules.d/ state=directory owner=root group=root mode=0700 recurse=yes
- name: copy iptables header
  template: src=000_header.rule dest=/etc/iptables/iptables.rules.d/ owner=root group=root mode=0700
- name: copy iptables footer
  template: src=zzz_footer.rule dest=/etc/iptables/iptables.rules.d/ owner=root group=root mode=0700
- name: Populate iptables file /etc/iptables/iptables.rules
  assemble: src=/etc/iptables/iptables.rules.d/ dest=/etc/iptables/iptables.rules validate="iptables-restore -t %s" owner=root group=root mode=0600
  register: iptables
- name: restart iptables
  service: name=iptables state=restarted
  when: iptables|changed
- name: enable iptables
  service: name=iptables state=started enabled=yes
