---
# defaults file for packt
cryptName: usbstorageDisk
pactRootDir: /srv/packt
pactLogFile: "{{ pactRootDir }}//log/packt.$(date '+%Y%m%d.%H%M%S').log"
packtDir: /media/{{ cryptName }}/data/ebooks
packtUSerAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
