---
# tasks file for smbserver
- name: install samba
  package: name=samba state=present
- name: configure samba
  template:
    src: etc/samba/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0500
  notify: restart samba
- name: add log dir
  file:
    path: /var/log/samba
    state: directory
    owner: root
    group: root
    mode: 0700
- name: start samba
  service:
    name: smb
    state: started
    enabled: yes
