---
# tasks file for mysql
- name: install mariadb
  pacmanneeded:  name=mariadb state=latest
  notify: restart mysqld
- name: install python2-mysql as dependency of ansible
  pacmanneeded:  name=mysql-python state=latest
- name: mysql_install_db
  command: /usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql creates=/var/lib/mysql/mysql
- name: prompt mysql Password
  pause: prompt="mysqlPassword is not defined, please enter the password for root in mysql set mysqlPassword in your playbook to avoid this"
  register: prompt_mysqlPassword
  when: mysqlPassword is not defined
- name: set mysql Password from input
  set_fact: mysqlPassword="{{prompt_mysqlPassword.user_input}}"
  when: mysqlPassword is not defined
- name: ensure mariadb is enabled
  service: name=mysqld enabled=yes state=started
  notify: restart nginx
##MySQL Hardening
- name: secure parameters in mariadb
  ini_file: dest=/etc/mysql/my.cnf section=mysqld option={{item.name}} value={{item.value}} backup=yes owner=root group=root mode=0644
  with_items:
    - {name: skip-grant-tables, value: 0}
    - {name: safe-user-create, value: 1}
    - {name: secure_auth, value: 1}
    - {name: secure_file_priv, value: '/tmp'}
    - {name: local_infile, value: 0}
    - {name: skip_name_resolve, value: 1}
    - {name: skip_show_database, value: 1}
    - {name: skip-symbolic-links, value: 1}
    - {name: expire_logs_days, value: "{{mysqlExpireLogsDays}}"}
  notify: restart mysqld
- name: set server id
  lineinfile: dest=/etc/mysql/my.cnf regexp=^server-id value="server-id = {{ansible_default_ipv4.address | regex_replace('\\.','')}}" owner=root group=root mode=0644
  notify: restart mysqld
- name: enable network for mysql on master
  ini_file: dest=/etc/mysql/my.cnf section=mysqld option=skip_networking value=0 owner=root group=root mode=0644
  when: "'master' in group_names"
  notify: restart mysqld
- name: disable network for mysql on slave
  ini_file: dest=/etc/mysql/my.cnf section=mysqld option=skip_networking value=1 owner=root group=root mode=0644
  when: "'slave' in group_names"
  notify: restart mysqld
- include: mysql_secure_installation.yml
- name: setup mysql replication
  include: mysql_replication.yml
- name: copy iptables rules for {{role_name}}
  template: src=etc/iptables/iptables.rules.d/role_{{role_name}}.rule dest=/etc/iptables/iptables.rules.d/ owner=root group=root mode=0700

