---
# handlers file for hardened
- name: apply sysctl
  shell: sysctl --system;sysctl -w net.ipv4.route.flush=1;sysctl -w net.ipv6.route.flush=1
- name: restart systemd-resolved
  service: name=systemd-resolved state=restarted
