---
# defaults file for monit
myDomain: example.com
monitUrl: "monitoring.{{myDomain}}"
cryptName: usbstorageDisk
additionalMounts: []
btrfsSubVolumes:
  - { name: 'data', mount: 'data'}
  - { name: 'backup', mount: 'backup'}
btrfsSubVolumesAdditionnals: []
monitCheckMounts: []
snapDir: snapshots
monitPort: 2812
monitUser: monit
monitPassword: "{{ lookup('password', 'credentials/common/' + role_name + '/pass') }}"
monitCheckUser: monit_checkuser
monitCheckPassword: "{{ lookup('password', 'credentials/common/' + role_name + '/passCheck') }}"
rootMail: "root@{{myDomain}}"
mailHubPort: 465
mailHost: "smtp.{{myDomain}}"
ssmtpHostname: "{{inventory_hostname_short}}.{{myDomain}}"
useTLS: "Yes"
ssmtpAuthUser: "{{rootMail}}"
ssmtpAuthPass: "{{ lookup('password', 'credentials/ssmtp/ssmtpAuthPass') }}"
mailHostIps: "{{ lookup('dig', mailHost, wantlist=True) }}"
monitMySQLUser: "monit_{{ lookup('password', 'credentials/' + ansible_hostname + '/' + role_name + '/monit_mysql_user chars=ascii_letters,digits length=10') }}"
monitMySQLPass: "{{ lookup('password', 'credentials/' + ansible_hostname + '/' + role_name + '/monit_mysql_password') }}"
rwDirectories:
  - {name: var, size: 10G, path: /var}
  - {name: opt, size: 1G, path: /opt}
  - {name: srv, size: 1G, path: /srv}
otherServers: "{{groups['all']}}"
letsencryptVirtualhosts: []
listVhosts: "{{letsencryptVirtualhosts|unique}}"
checkHttpsOptions: {}
