- name: create directory /etc/iptables/iptables.rules.d/
  file: path=/etc/iptables/iptables.rules.d/ state=directory owner=root group=root mode=0700 recurse=yes
- name: set role_name fact
  set_fact: role_name= "{{ lookup('pipe','pwd')|dirname|basename }}"
- name: copy iptables rules for {{ role_name }}
  template: src=etc/iptables/iptables.rules.d/role_{{ role_name }}.rule dest=/etc/iptables/iptables.rules.d/ owner=root group=root mode=0700
  when: "'master' in group_names"
  register: iptables
#input port 80 can be filtered and so we need to restart iptables
- name: Populate iptables file /etc/iptables/iptables.rules
  shell: cat /etc/iptables/iptables.rules.d/*.rule > /etc/iptables/iptables.rules
  when: iptables is changed
- name: restart iptables
  service: name=iptables state=restarted
  when: iptables is changed
- name: delete iptables rules for slave
  copy: content="#iptables for {{ role_name }} is disabled for slave\\n" dest=/etc/iptables/iptables.rules.d/role_{{ role_name }}.rule owner=root group=root mode=0700
  when: "'slave' in group_names"
